### ISSUE TITLE
Do you have a script to download the datasets?

### ISSUE THREAD

**Issue by Becomebright** [csteinmetz1/wavebeat#2]
Thanks for your work. I encountered some problems when trying to download the datasets. Do you have a script or any instructions to download the datasets?

**Comment by csteinmetz1** [comment]
Hey @Becomebright, thanks for checking out the repo. Unfortunately we do not have download scripts for the datasets since many are private or have licenses that do not permit us to share them. This is one big challenge with beat tracking datasets I found while working on this project.
